services:
  mirror-ai:
    image: fr-mirror-ai
    container_name: mirror-ai
    restart: unless-stopped
    ports:
      - "${access_port}:80" 
    env_file:
      - .env
    environment:
      - XAI_API_KEY=${xai_api_key}
    networks:
      - ${network}

networks:
  mirror-network:
    driver: bridge