services:
  mirror-ai:
    image: fr-mirror-ai
    container_name: mirror-ai
    restart: unless-stopped
    ports:
      - "${PORT}:80"  # Assuming the container exposes port 8080 internally
    volumes:
      - .:/code
    env_file:
      - .env
    networks:
      - mirror-network

networks:
  mirror-network:
    driver: bridge